### PR TITLE
fix(examples/coap): Various fixes

### PR DESCRIPTION
**Pull request by chrysn**
# Description

These are simple fixes taken out of https://github.com/future-proof-iot/RIOT-rs/pull/348 – that PR is going back a few steps because I took a wrong turn, and this now I'm consolidating things into manageable changes.

This does introduce one FIXME, but the need for getting that piece of information was already there and just hidden by the broken code.

## Change checklist

- [x] I have cleaned up my commit history and squashed fixup commits.
- [x] I have followed the [Coding Conventions](https://future-proof-iot.github.io/RIOT-rs/dev/docs/book/coding-conventions.html).
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by kaspar030** [comment]
Depends on #469.

**Comment by chrysn** [comment]
I'm on that in parallel, but that's running through tests time and again. I did do a full local build test of the CoAP example, and exceeding what CI did also with and without IPv6 enabled.

Code that is not in CI has a tendency to rot, let's fix this in parallel. Even with no CI running, this PR makes the code better, and reduces the warnings I'm sifting through while looking for hints at what is keeping #469 back.

**Comment by kaspar030** [comment]
> I'm on that in parallel, but that's running through tests time and again. I did do a full local build test of the CoAP example, and exceeding what CI did also with and without IPv6 enabled.

ok!

**Comment by kaspar030** [comment]
LGTM.

**Pull request merged**
